# Generated by Django 5.0.6 on 2024-06-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automator_app', '0002_device_ipv4_address_device_model_device_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ipv4_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='model',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
