# Generated by Django 5.0.6 on 2024-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automator_app', '0003_alter_device_ipv4_address_alter_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='street_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
